name: release

on:
  release:
    types: 
    - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        docker login -u "${QUAY_USER}" -p "${QUAY_PASS}" quay.io
        IMAGE_NAME="quay.io/nunnatsa/readfromfile:${GITHUB_REF##*/}"
        docker build -t "${IMAGE_NAME}" .
        docker push "${IMAGE_NAME}"
